### ISSUE TITLE
High frequency mezzanine

### ISSUE THREAD

**Issue by cjbe** [sinara-hw/Almazny#1]
How far advanced are the plans for the high frequency mezzanine?

I need some sources around 5-12 GHz for which Mirny+mezzanine would be ideal. For my use case all I would require on the mezzanine is matching and switching. Switchable attenuation would be a nice to have.

Does anyone have any appetite to specify / use / build this? If so I can put some effort into crystallising specifications.

**Comment by cjbe** [comment]
@gkasprow @shanasz any idea when we will be able to get some hardware made? I am keen to try Almazny out!

**Comment by gkasprow** [comment]
It's already finished, @shanasz can we produce it?

**Comment by cjbe** [comment]
I see a production release! @gkasprow what is the best way of getting hold of one once smoke tests pass?
