### ISSUE TITLE
Invalid IC9 EN connection

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Almazny#11]
![image](https://user-images.githubusercontent.com/9166701/203112044-0b158b5a-906f-4d18-952e-907b0a120667.png)

**Comment by gkasprow** [comment]
good catch!

**Comment by gkasprow** [comment]
fixed
![obraz](https://user-images.githubusercontent.com/4325054/223845699-83dd2131-fa1d-40f2-a469-d74660ba2df9.png)
