### ISSUE TITLE
missing mounting HW

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Almazny#4]
@shanasz please add to the BOM
- mounting screws + washers + standoffs (copy if from Stabilizer mezzanine)
- SMP bullets

**Comment by jordens** [comment]
IME the screw heads on the mirny underside are thicker than allowed and interfere with the adjacent panel's gasket. Same on stabilizer/pounder. Is there something we can do?

**Comment by jordens** [comment]
You had some really nice soldered or press-fit standoffs or screws on dio-mcx IIRC. Those would be great.

**Comment by gkasprow** [comment]
yes, but here I need nontypical height. These inserts are available only in 1mm increments
I used such in the Thermostat EEM design. DIO_MCX has classical ones since non-typical height was needed as well.
