### ISSUE TITLE
front panel bumps into SMA connectors

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Almazny#5]
Dirty dremel solution:
![image](https://user-images.githubusercontent.com/720864/127736937-c992ed02-9d48-4d27-9e1b-b109fc367c36.png)

**Comment by gkasprow** [comment]
common panel with Mirny will solve the issue.

**Comment by gkasprow** [comment]
@jordens this is a common panel design. Any comment?
![obraz](https://user-images.githubusercontent.com/4325054/174909056-c1d596df-8e19-4f9e-8150-d8c683192a8d.png)

**Comment by jordens** [comment]
* Maybe add the LEDs mentioned in https://github.com/sinara-hw/Almazny/issues/7#issuecomment-1163261142
* Maybe also an additional LED for Almazny PGOOD.
* Below "HF MEZZANINE" there is space for "2X LF FREQUENCY"
* There should be two version numbers at the bottom. I know it is tricky. But let's put v1.2 for Mirny and v1.1 for Almazny (and call them like that).

**Comment by jordens** [comment]
Very good.
Are you sure about the version numbers? Shouldn't this be Almazny 1.1?

**Comment by jordens** [comment]
As long as files, front panel and board markings are consistent for the next version, it's fine.

**Comment by jordens** [comment]
Fixed by common panel
