### ISSUE TITLE
v1.2

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Almazny#8]
What's the level of interest in a v2 redesign?
The most pressing issues appear to be:

* #7 (to be discussed) combined with https://github.com/quartiq/mirny/pull/5 to refactor the interface such that it integrates cleaner into the carrier/gateware
* #3 a blocker
* #5 panel design

**Comment by gkasprow** [comment]
@shanasz  is working on them. Please make a commit.

**Comment by jordens** [comment]
@shanasz ping

**Comment by jordens** [comment]
@shanasz ping again

**Comment by jordens** [comment]
@shanasz ping

**Comment by gkasprow** [comment]
I updated v1.2 design files

**Comment by gkasprow** [comment]
I also added new release

**Comment by jordens** [comment]
Thanks!
LGTM
